#!/usr/bin/env bash

append_line() {
	file=$1
	line=$2
	echo "$line" >> "$file"
}

sort_in_place() {
	file=$1
	unsorted_file="$1_unsorted"

	mv "$file" "$unsorted_file"
	sort "$unsorted_file" > "$file"
	rm "$unsorted_file"
}

uniq_in_place() {
	file=$1
	duplicated_file="$1_duplicated"

	mv "$file" "$duplicated_file"
	uniq "$duplicated_file" > "$file"
	rm "$duplicated_file"
}

package=$1

append_line "packages" "$package"
sort_in_place "packages"
uniq_in_place "packages"
