#!/usr/bin/env python3

from pathlib import Path

def link_all(paths, remote_dir):
	for path in paths:
		local_path = Path.cwd().joinpath(path)
		remote_path = remote_dir.joinpath(path)

		if not local_path.exists():
			print(f"{local_path} does not exist, skipping")
			continue

		if remote_path.exists():
			print(f"{remote_path} already exists, skipping")
			continue

		remote_path.symlink_to(local_path)
		print(f"Linked {remote_path} to {local_path}")

home_paths = [
	"bin/",
	".vim/",
	".bashrc",
	".gitconfig",
	".gitignore",
	".inputrc",
	".profile",
	".tool-versions",
	".vimrc",
	".Xmodmap",
	".xinitrc",
	".Xresources"
]

xdg_paths = [
	"i3/",
	"i3status/"
]


link_all(home_paths, remote_dir=Path.home())
link_all(xdg_paths, remote_dir=Path.home().joinpath(".config/"))
